
# ??????
# ??????
server:
  # ????HTTP??????8080
  port: 9090
  servlet:
    # ???????
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # tomcat?????????200
    max-threads: 800
    # Tomcat?????????????25
    min-spare-threads: 30

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: postgres
    password: 123456




